name       : godot-cpp
version    : 3.5.2
release    : 8
source     :
    - https://github.com/godotengine/godot-cpp/archive/refs/tags/godot-3.5.2-stable.tar.gz : 73748396b0ad3789b7fcff815dfead47b022902199c8708341c263402f263f19
license    : MIT
component  : programming.devel
summary    : C++ bindings for the Godot script API
description: |
    The C++ bindings for GDNative are built on top of the NativeScript GDNative API and provide a nicer way to "extend" nodes in Godot using C++. This is equivalent to writing scripts in GDScript, but in C++ instead.
clang      : yes
builddeps  :
    - godot-headers
    - scons
rundeps    :
    - godot-headers
setup      : |
    sed "s/@VERSION@/%version%/" $pkgfiles/godot-cpp.pc.in > godot-cpp.pc
    rm -rf godot-headers
    cp -r /usr/include/godot godot-headers
build      : |
    python3 /usr/bin/scons %JOBS% platform=linux use_llvm=yes generate_bindings=yes target=release
install    : |
    install -dm00755 $installdir/usr/{lib64,include}
    install -Dm00644 bin/libgodot-cpp.linux.*.a $installdir/usr/lib64/libgodot-cpp.a
    install -Dm00644 godot-cpp.pc $installdir/usr/lib64/pkgconfig/godot-cpp.pc
    cp -rup include $installdir/usr/include/godot
patterns   :
    - /*
